# Generated by Django 4.1.2 on 2022-11-16 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab6', '0003_alter_user_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=100)),
                ('nationalID', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
