# Generated by Django 4.1.2 on 2022-11-16 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab6', '0004_feedback_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_card', models.CharField(max_length=19)),
                ('pin', models.IntegerField()),
            ],
        ),
    ]
